version: '3.7'

networks:
  jenkins:
    driver: bridge

services:

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 9000:9000
      - 80:80
    networks:
      - jenkins
    volumes:
      - ./nginx/:/etc/nginx/conf.d/

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheuss
    networks:
      - jenkins
    ports:
      - 9091:9090
    volumes:
      - ./prometheus-config/:/etc/prometheus/

  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - prometheus
    networks:
      - jenkins
    environment:
      - GF_SERVER_HTTP_PORT=3030
    ports:
      - 3031:3030