node {
    
    env.CI = 'true'

    def dockerImage = 'node:16-buster-slim'

    docker.image(dockerImage).inside("-p 3000:3000") {
        echo "Building..."
        try {
            stage('Build') {
                sh 'npm install'
            }
        } catch(Exception e) {
            currentBuild.result = 'FAILURE'
            error "Build failed: ${e.message}"
        }
    }

    docker.image(dockerImage).inside("-p 3000:3000") { 
        try {

            echo "Testing..."

            stage('Test') {
                sh './jenkins/scripts/test.sh'
            }

            echo "Deliver..."

            stage('Deliver') {
                sh './jenkins/scripts/deliver.sh'
                // Manual input from user
                input message: 'Finished using the website? (Click "Proceed" to continue)'
                sh './jenkins/scripts/kill.sh'
            }
        } catch(Exception e) {
            currentBuild.result = 'FAILURE'
            throw e
        }
    }

}