node {


    // Define environment variables
    env.CI = 'true'
    env.CD = 'true'
    

    // Use Docker container for the pipeline
    docker.image('node:lts-buster').inside('-p 3000:3000') {

        try {

            stage('Checkout') {
                checkout scm
            }

            // Build stage
            stage('Build') {
                sh 'npm cache clean --force'
                sh 'npm install'
            }

            // Test stage
            stage('Test') {
                sh './jenkins/scripts/test.sh'
            }

            // Manual Approval stage
            stage('Manual Approval') {
                // Manual input from user
                input message: 'Lanjutkan ke tahap Deploy ? (Click "Proceed" to continue)'
            }

            // Deliver stage
            stage('Deploy') {
                sh './jenkins/scripts/deliver.sh'
                sleep 60
                sh './jenkins/scripts/kill.sh'
            }

        } catch (Exception e) {
            
            // If any stage fails, catch the exception and mark the build as failed
            currentBuild.result = 'FAILURE'
            throw e  // Re-throw the exception to fail the build

        } finally {

            if (currentBuild.result != "FAILURE") {
                // push to artifact
                archiveArtifacts 'build/*'
            }
        }
    }
}